/**
 * NotesManager
 *
 * Manages user notes - both manual and AI-generated.
 * Handles note persistence to MongoDB and AI generation from transcripts.
 */

import { SyncedManager, synced, rpc } from "../../../lib/sync";
import { Note, createNote, getNotes, updateNote, deleteNote, getDailyTranscript, deleteTrashedNotes } from "../../models";
import {
  createProviderFromEnv,
  isProviderAvailable,
  type AgentProvider,
  type UnifiedMessage,
} from "../../services/llm";
import type { TranscriptSegment } from "./TranscriptManager";
import type { FileManager } from "./FileManager";
import { TimeManager } from "./TimeManager";

// =============================================================================
// Types
// =============================================================================

export interface NoteData {
  id: string;
  title: string;
  content: string;
  summary?: string;
  date: string; // Folder date in YYYY-MM-DD format (which day this note belongs to)
  isAIGenerated: boolean; // Whether this note was generated by AI or created manually
  isFavourite: boolean;
  isArchived: boolean;
  isTrashed: boolean;
  folderId?: string | null; // Optional folder assignment
  createdAt: Date;
  updatedAt: Date;
  transcriptRange?: {
    startTime: Date;
    endTime: Date;
  };
}

// =============================================================================
// Helpers
// =============================================================================

/**
 * Convert any stray markdown syntax the LLM slipped into the note body into
 * the HTML tags TipTap expects. Also wraps bare text lines in <p>.
 *
 * The prompt tells the model "HTML only, no markdown" but providers still
 * occasionally emit `**bold**`, `## heading`, or `- item` lines. TipTap
 * renders those as literal characters, so we normalize server-side before
 * persisting the note.
 */
function normalizeToHtml(raw: string): string {
  if (!raw) return raw;

  // If the output already looks like clean HTML (has block tags and no
  // obvious markdown markers), still run a light pass to catch inline **bold**.
  let html = raw.trim();

  // Strip any leading/trailing code fences the LLM might wrap output in.
  html = html.replace(/^```(?:html)?\s*\n?/i, "").replace(/\n?```\s*$/i, "");

  // Inline conversions — safe to run on HTML too (no `**` exists in valid HTML).
  //   **bold** / __bold__ → <strong>bold</strong>
  html = html.replace(/\*\*([^*\n]+?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/__([^_\n]+?)__/g, "<strong>$1</strong>");
  //   *italic* / _italic_ → <em>italic</em>   (skip if adjacent to word chars to avoid false positives)
  html = html.replace(/(^|[\s>])\*([^*\n]+?)\*(?=[\s<.,!?;:]|$)/g, "$1<em>$2</em>");
  html = html.replace(/(^|[\s>])_([^_\n]+?)_(?=[\s<.,!?;:]|$)/g, "$1<em>$2</em>");

  // If the body already has block-level HTML tags, don't touch line structure.
  const hasBlockTags = /<(h[1-6]|p|ul|ol|li|img|div)\b/i.test(html);
  if (hasBlockTags) return html;

  // Otherwise, model gave us a markdown-ish document. Convert block structure.
  const lines = html.split(/\r?\n/);
  const out: string[] = [];
  let inList = false;

  const closeList = () => {
    if (inList) {
      out.push("</ul>");
      inList = false;
    }
  };

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) {
      closeList();
      continue;
    }

    // Headings: `# `, `## `, `### `
    const headingMatch = line.match(/^(#{1,3})\s+(.+)$/);
    if (headingMatch) {
      closeList();
      const level = Math.min(headingMatch[1].length + 1, 6); // bump `#` → <h2> (we never use <h1>)
      out.push(`<h${level}>${headingMatch[2]}</h${level}>`);
      continue;
    }

    // Bullet list items: `- `, `* `, `• `
    const bulletMatch = line.match(/^[-*•]\s+(.+)$/);
    if (bulletMatch) {
      if (!inList) {
        out.push("<ul>");
        inList = true;
      }
      out.push(`<li>${bulletMatch[1]}</li>`);
      continue;
    }

    // Regular paragraph
    closeList();
    out.push(`<p>${line}</p>`);
  }

  closeList();
  return out.join("\n");
}

// =============================================================================
// Manager
// =============================================================================

export class NotesManager extends SyncedManager {
  @synced notes = synced<NoteData[]>([]);
  @synced generating = false;

  private provider: AgentProvider | null = null;
  private timeManager: TimeManager | null = null;

  // ===========================================================================
  // Private Helpers
  // ===========================================================================

  private getTimeManager(): TimeManager {
    if (!this.timeManager) {
      const timezone = (this._session as any).appSession?.settings?.getMentraOS(
        "userTimezone",
      ) as string | undefined;
      this.timeManager = new TimeManager(timezone);
    }
    return this.timeManager;
  }

  /**
   * Load transcript segments for a specific date from MongoDB or R2.
   */
  private async loadSegmentsForDate(date: string): Promise<TranscriptSegment[]> {
    const userId = this._session?.userId;
    if (!userId) return [];

    try {
      // Try MongoDB first
      const dailyTranscript = await getDailyTranscript(userId, date);
      if (dailyTranscript?.segments?.length) {
        return dailyTranscript.segments.map((s, i) => ({
          id: `seg_${date}_${i}`,
          text: s.text,
          timestamp: s.timestamp,
          isFinal: s.isFinal,
          speakerId: s.speakerId,
          type: s.type,
          photoUrl: s.photoUrl,
          photoMimeType: s.photoMimeType,
          photoDescription: s.photoDescription,
          timezone: s.timezone,
        }));
      }

      // Fallback to R2
      const r2Manager = (this._session as any)?.r2;
      if (r2Manager) {
        const r2Data = await r2Manager.fetchTranscript(date);
        if (r2Data?.segments?.length) {
          return r2Data.segments.map((seg: any, idx: number) => ({
            id: `seg_${seg.index || idx + 1}`,
            text: seg.text,
            timestamp: new Date(seg.timestamp),
            isFinal: seg.isFinal,
            speakerId: seg.speakerId,
            type: seg.type,
            photoUrl: seg.photoUrl,
            photoMimeType: seg.photoMimeType,
            photoDescription: seg.photoDescription,
            timezone: seg.timezone,
          }));
        }
      }
    } catch (error) {
      console.error(`[NotesManager] Failed to load segments for ${date}:`, error);
    }

    return [];
  }

  private getFileManager(): FileManager | null {
    return (this._session as any)?.file || null;
  }

  private getNoteDate(note: NoteData): string {
    // Use the note's date field (folder date) if available, otherwise derive from createdAt
    if (note.date) {
      return note.date;
    }
    return this.getTimeManager().toDateString(new Date(note.createdAt));
  }

  private getProvider(): AgentProvider | null {
    if (this.provider) return this.provider;

    if (!isProviderAvailable("gemini") && !isProviderAvailable("anthropic")) {
      console.warn("[NotesManager] No AI provider available");
      return null;
    }

    try {
      this.provider = createProviderFromEnv();
      return this.provider;
    } catch (error) {
      console.error("[NotesManager] Failed to create AI provider:", error);
      return null;
    }
  }

  // ===========================================================================
  // Lifecycle
  // ===========================================================================

  async hydrate(): Promise<void> {
    const userId = this._session?.userId;
    if (!userId) return;

    try {
      const dbNotes = await getNotes(userId);

      if (dbNotes.length > 0) {
        const loadedNotes: NoteData[] = dbNotes.map((n) => {
          let title = n.title;

          // Recover title for notes corrupted by the old persistNoteUpdate bug
          if (!title && (n.content || n.summary)) {
            const html = n.content || n.summary || "";
            // Try extracting from first heading
            const headingMatch = html.match(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/i);
            if (headingMatch?.[1]) {
              title = headingMatch[1].replace(/<[^>]+>/g, "").trim();
            } else {
              // Fall back to first few words of plain text
              const plainText = html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
              title = plainText.split(" ").slice(0, 6).join(" ");
              if (plainText.split(" ").length > 6) title += "...";
            }
            // Persist the recovered title back to DB
            if (title && n._id) {
              updateNote(userId, n._id.toString(), { title }).catch(() => {});
            }
          }

          return {
            id: n._id?.toString() || `note_${Date.now()}`,
            title: title || "",
            content: n.content || n.summary || "",
            summary: n.summary,
            date: n.date || this.getTimeManager().toDateString(n.createdAt),
            isAIGenerated: n.isAIGenerated ?? false,
            isFavourite: n.isFavourite ?? n.isStarred ?? false,
            isArchived: n.isArchived ?? false,
            isTrashed: n.isTrashed ?? false,
            folderId: n.folderId || null,
            createdAt: n.createdAt,
            updatedAt: n.updatedAt,
            transcriptRange: n.transcriptRange,
          };
        });

        this.notes.set(loadedNotes);
        console.log(
          `[NotesManager] Hydrated ${loadedNotes.length} notes for ${userId}`,
        );
      }
    } catch (error) {
      console.error("[NotesManager] Failed to hydrate:", error);
    }
  }

  // ===========================================================================
  // Persistence Helpers
  // ===========================================================================

  private getTranscriptLoadedDate(): string | null {
    const transcriptManager = (this._session as any)?.transcript;
    return transcriptManager?.loadedDate || null;
  }

  private async persistNote(note: NoteData, targetDate?: string): Promise<string> {
    const userId = this._session?.userId;
    if (!userId) return note.id;

    // Determine the folder date for this note
    // Use targetDate if provided (e.g., transcript's date), otherwise derive from note's createdAt
    const noteDate = targetDate || this.getNoteDate(note);

    try {
      const dbNote = await createNote(userId, {
        title: note.title,
        summary: note.summary || "",
        content: note.content,
        date: noteDate, // Store the folder date explicitly
        isAIGenerated: note.isAIGenerated,
        transcriptRange: note.transcriptRange,
      });

      // Notify FileManager about the new note
      const fileManager = this.getFileManager();
      if (fileManager) {
        await fileManager.onNoteCreated(noteDate);
      }

      return dbNote._id?.toString() || note.id;
    } catch (error) {
      console.error("[NotesManager] Failed to persist note:", error);
      return note.id;
    }
  }

  private async persistNoteUpdate(
    noteId: string,
    updates: Partial<NoteData>,
  ): Promise<void> {
    const userId = this._session?.userId;
    if (!userId) return;

    try {
      const dbUpdates: Record<string, unknown> = {};
      if (updates.title !== undefined) dbUpdates.title = updates.title;
      if (updates.summary !== undefined) dbUpdates.summary = updates.summary;
      if (updates.content !== undefined) dbUpdates.content = updates.content;
      if (updates.folderId !== undefined) dbUpdates.folderId = updates.folderId;
      if (updates.isFavourite !== undefined) dbUpdates.isFavourite = updates.isFavourite;
      if (updates.isArchived !== undefined) dbUpdates.isArchived = updates.isArchived;
      if (updates.isTrashed !== undefined) dbUpdates.isTrashed = updates.isTrashed;

      await updateNote(userId, noteId, dbUpdates);
    } catch (error) {
      console.error("[NotesManager] Failed to update note in DB:", error);
    }
  }

  private async persistNoteDelete(noteId: string, noteDate: string): Promise<void> {
    const userId = this._session?.userId;
    if (!userId) return;

    try {
      await deleteNote(userId, noteId);

      // Notify FileManager about the deleted note
      const fileManager = this.getFileManager();
      if (fileManager) {
        await fileManager.onNoteDeleted(noteDate);
      }
    } catch (error) {
      console.error("[NotesManager] Failed to delete note from DB:", error);
    }
  }

  // ===========================================================================
  // RPC Methods
  // ===========================================================================

  @rpc
  async generateNote(
    title?: string,
    startTime?: Date | string,
    endTime?: Date | string,
  ): Promise<NoteData> {
    this.generating = true;

    const startDate = startTime
      ? typeof startTime === "string"
        ? new Date(startTime)
        : startTime
      : undefined;
    const endDate = endTime
      ? typeof endTime === "string"
        ? new Date(endTime)
        : endTime
      : undefined;

    try {
      // Get transcript context — try in-memory first, then MongoDB, then R2
      const transcriptManager = (this._session as any)?.transcript;
      let segments: TranscriptSegment[] = transcriptManager?.segments ?? [];

      // For historical dates, load segments from MongoDB/R2
      if (startDate) {
        const segmentDate = this.getTimeManager().toDateString(startDate);
        const today = this.getTimeManager().today();

        if (segmentDate !== today || segments.length === 0) {
          segments = await this.loadSegmentsForDate(segmentDate);
        }
      }

      // Filter segments by time range if provided
      let relevantSegments = segments;
      if (startDate || endDate) {
        const filtered = segments.filter((seg) => {
          const segTime = new Date(seg.timestamp).getTime();
          const afterStart = !startDate || segTime >= startDate.getTime();
          const beforeEnd = !endDate || segTime <= endDate.getTime();
          return afterStart && beforeEnd;
        });
        console.log(`[NotesManager] Time filter: ${filtered.length}/${segments.length} segments match range`);
        // If time filter returns nothing but we have segments, use all segments for the date
        // (handles timezone mismatches between conversation and transcript timestamps)
        if (filtered.length > 0) {
          relevantSegments = filtered;
        } else if (segments.length > 0) {
          console.log(`[NotesManager] Time filter matched 0 segments — falling back to all ${segments.length} segments for the date`);
          relevantSegments = segments;
        }
      }

      // Build transcript text, skipping photo placeholder text
      const transcriptText = relevantSegments
        .filter((s) => s.type !== "photo")
        .map((s) => s.text)
        .join(" ");

      // Collect photos with descriptions from segments
      const photos = relevantSegments
        .filter((s) => s.type === "photo" && s.photoUrl)
        .map((s) => ({ url: s.photoUrl!, description: s.photoDescription || "No description" }));
      const photoUrls = photos.map((p) => p.url);

      if (!transcriptText.trim() && photoUrls.length === 0) {
        throw new Error("No transcript content to generate note from");
      }

      let summary = "";
      let generatedTitle = title;

      const provider = this.getProvider();
      if (provider && (transcriptText.length > 50 || photoUrls.length > 0)) {
        try {
          const photoInstruction = photos.length > 0
            ? `\n- You have ${photos.length} photo(s) available. Include a photo ONLY if it is relevant to the surrounding note content. Use <img> tags with the exact URLs provided. Omit photos that don't add value to the notes.\n${photos.map((p, i) => `  Photo ${i + 1}: ${p.url}\n    Description: ${p.description}`).join("\n")}`
            : "";

          const messages: UnifiedMessage[] = [
            {
              role: "user",
              content: `Create a structured note from this transcript.

Requirements:
- Between 100-500 words
- Use <h2> headings to organize by topic
- Use bullet lists for key points
- Bold important terms with <strong>
- Output valid HTML only (no markdown)
- Do NOT include sections like "Key Decisions", "Action Items", "Conclusion", or "Next Steps" — just organize naturally by topic${photoInstruction}

Transcript:
${transcriptText || "(No speech transcript - only photos captured)"}

${title ? `Title to use: "${title}"` : "Also generate an appropriate title."}

Response format:
TITLE: [title here]
CONTENT:
[HTML content here]`,
            },
          ];

          const response = await provider.chat(messages, {
            tier: "fast",
            maxTokens: 2048,
            systemPrompt: `You are a note-taking assistant that creates well-structured notes from transcripts.

CRITICAL: Output raw HTML only. Do NOT output markdown. The output is rendered directly by a TipTap HTML editor — any markdown syntax will appear to the user as literal text (e.g. \`**word**\` renders as the four characters \`*\`, \`*\`, \`w\`…, not as bold).

Allowed tags (use ONLY these):
- <h2> for section headings
- <p> for paragraphs — every paragraph MUST be wrapped in <p>...</p>
- <strong> for bold/important text — NEVER use **text** or __text__
- <em> for italic text — NEVER use *text* or _text_
- <ul> and <li> for bulleted lists — NEVER use "- item" or "* item" lines
${photos.length > 0 ? "- <img> for photos (use the exact URLs provided, do NOT invent URLs)\n\nPhoto rules:\n- Only include a photo if it is relevant to the note content\n- Place photos near the text they relate to\n- If a photo doesn't relate to any section, leave it out" : ""}

Correct example:
<h2>Project Overview</h2>
<p>The project revolves around <strong>AI motion graphics</strong>.</p>
<ul>
  <li><strong>Integration</strong>: connects to Claude.</li>
  <li><strong>Functionality</strong>: users specify what to generate.</li>
</ul>

Wrong example (DO NOT do this):
## Project Overview
The project revolves around **AI motion graphics**.
- **Integration**: connects to Claude.

Rules:
- Write between 100-500 words
- Focus on key points and important details
- Use headings to organize by topic naturally
- Use bullet lists for multiple related items
- Bold important names, dates, or key terms
- Do NOT add formulaic sections like "Key Decisions", "Action Items", "Conclusion", or "Next Steps"`,
          });

          const responseText =
            typeof response.content === "string"
              ? response.content
              : response.content
                  .filter((c) => c.type === "text")
                  .map((c) => (c as any).text)
                  .join("");

          // Parse title — try multiple patterns since LLM format varies
          const titleMatch = responseText.match(
            /TITLE:\s*(.+?)(?:\r?\n|CONTENT:)/s,
          ) || responseText.match(
            /^#\s*(.+?)$/m,
          );
          const contentMatch = responseText.match(/CONTENT:\s*([\s\S]+)$/);

          if (titleMatch?.[1]?.trim()) {
            const parsed = titleMatch[1].trim().replace(/^["']|["']$/g, "");
            if (!title) {
              generatedTitle = parsed;
            }
          }
          if (contentMatch) {
            summary = contentMatch[1].trim();
          } else if (!contentMatch && responseText.includes("<")) {
            // LLM skipped CONTENT: prefix, try to extract HTML directly
            const htmlStart = responseText.indexOf("<");
            if (htmlStart !== -1) {
              summary = responseText.substring(htmlStart).trim();
            }
          } else if (!contentMatch) {
            // LLM returned markdown or plain text with no CONTENT: prefix either.
            // Everything after the TITLE line (if any) is note body.
            const afterTitle = responseText.replace(/^TITLE:[^\n]*\n?/i, "").trim();
            summary = afterTitle || responseText.trim();
          }

          // Safety net: normalize any stray markdown the LLM slipped in
          // (despite the HTML-only instruction) so TipTap renders correctly.
          summary = normalizeToHtml(summary);

        } catch (error) {
          console.error("[NotesManager] AI generation failed:", error);
          const photoHtml = photoUrls.map((url) => `<img src="${url}">`).join("\n");
          summary = `<p>${transcriptText.length > 500 ? transcriptText.substring(0, 500) + "..." : transcriptText}</p>${photoHtml}`;
        }
      } else {
        const photoHtml = photoUrls.map((url) => `<img src="${url}">`).join("\n");
        summary = `<p>${transcriptText.length > 500 ? transcriptText.substring(0, 500) + "..." : transcriptText}</p>${photoHtml}`;
      }

      const now = new Date();
      // Use the transcript's loaded date for folder assignment
      // This ensures notes generated from historical transcripts go to the correct folder
      const transcriptDate = this.getTranscriptLoadedDate() || this.getTimeManager().today();

      const note: NoteData = {
        id: `note_${Date.now()}`,
        title: generatedTitle || title || `Note - ${now.toLocaleTimeString()}`,
        content: summary || `<p>${transcriptText.substring(0, 500)}...</p>`,
        summary: "",
        date: transcriptDate,
        isAIGenerated: true,
        isFavourite: false,
        isArchived: false,
        isTrashed: false,
        createdAt: now,
        updatedAt: now,
        transcriptRange:
          startDate && endDate
            ? { startTime: startDate, endTime: endDate }
            : relevantSegments.length > 0
              ? {
                  startTime: new Date(relevantSegments[0].timestamp),
                  endTime: new Date(
                    relevantSegments[relevantSegments.length - 1].timestamp,
                  ),
                }
              : undefined,
      };

      const dbId = await this.persistNote(note, transcriptDate);
      note.id = dbId;

      this.notes.mutate((n) => n.unshift(note));
      return note;
    } finally {
      this.generating = false;
    }
  }

  @rpc
  async createManualNote(title: string, content: string): Promise<NoteData> {
    const now = new Date();
    // Use the transcript's loaded date for folder assignment
    // This ensures manual notes created while viewing a historical date go to that folder
    const transcriptDate = this.getTranscriptLoadedDate() || this.getTimeManager().today();

    const note: NoteData = {
      id: `note_${Date.now()}`,
      title: title || "Untitled Note",
      content,
      summary:
        content.length > 200 ? content.substring(0, 200) + "..." : content,
      date: transcriptDate,
      isAIGenerated: false,
      isFavourite: false,
      isArchived: false,
      isTrashed: false,
      createdAt: now,
      updatedAt: now,
    };

    const dbId = await this.persistNote(note, transcriptDate);
    note.id = dbId;

    this.notes.mutate((n) => n.unshift(note));
    return note;
  }

  @rpc
  async updateNote(noteId: string, updates: Partial<NoteData>): Promise<NoteData> {
    let updatedNote: NoteData | null = null;

    this.notes.mutate((notes) => {
      const index = notes.findIndex((n) => n.id === noteId);
      if (index !== -1) {
        notes[index] = {
          ...notes[index],
          ...updates,
          updatedAt: new Date(),
        };
        updatedNote = notes[index];
      }
    });

    if (!updatedNote) {
      throw new Error(`Note not found: ${noteId}`);
    }

    await this.persistNoteUpdate(noteId, updates);

    return updatedNote;
  }

  @rpc
  async deleteNote(noteId: string): Promise<void> {
    // Find the note first to get its date
    const note = this.notes.find((n) => n.id === noteId);
    const noteDate = note ? this.getNoteDate(note) : null;

    this.notes.set(this.notes.filter((n) => n.id !== noteId));

    if (noteDate) {
      await this.persistNoteDelete(noteId, noteDate);
    }

    // Clear noteId link from any conversation that referenced this note
    const conversationManager = (this._session as any)?.conversation;
    if (conversationManager?.clearNoteLink) {
      conversationManager.clearNoteLink(noteId);
    }
  }

  @rpc
  async getNoteById(noteId: string): Promise<NoteData | null> {
    return this.notes.find((n) => n.id === noteId) || null;
  }

  @rpc
  async getAllNotes(): Promise<NoteData[]> {
    return [...this.notes];
  }

  @rpc
  async favouriteNote(noteId: string): Promise<void> {
    this.notes.mutate((notes) => {
      const idx = notes.findIndex((n) => n.id === noteId);
      if (idx >= 0) { notes[idx].isFavourite = true; notes[idx].isArchived = false; notes[idx].isTrashed = false; }
    });
    await this.persistNoteUpdate(noteId, { isFavourite: true, isArchived: false, isTrashed: false });
  }

  @rpc
  async unfavouriteNote(noteId: string): Promise<void> {
    this.notes.mutate((notes) => {
      const idx = notes.findIndex((n) => n.id === noteId);
      if (idx >= 0) notes[idx].isFavourite = false;
    });
    await this.persistNoteUpdate(noteId, { isFavourite: false });
  }

  @rpc
  async archiveNote(noteId: string): Promise<void> {
    this.notes.mutate((notes) => {
      const idx = notes.findIndex((n) => n.id === noteId);
      if (idx >= 0) { notes[idx].isArchived = true; notes[idx].isFavourite = false; notes[idx].isTrashed = false; }
    });
    await this.persistNoteUpdate(noteId, { isArchived: true, isFavourite: false, isTrashed: false });
  }

  @rpc
  async unarchiveNote(noteId: string): Promise<void> {
    this.notes.mutate((notes) => {
      const idx = notes.findIndex((n) => n.id === noteId);
      if (idx >= 0) notes[idx].isArchived = false;
    });
    await this.persistNoteUpdate(noteId, { isArchived: false });
  }

  @rpc
  async trashNote(noteId: string): Promise<void> {
    this.notes.mutate((notes) => {
      const idx = notes.findIndex((n) => n.id === noteId);
      if (idx >= 0) { notes[idx].isTrashed = true; notes[idx].isFavourite = false; notes[idx].isArchived = false; }
    });
    await this.persistNoteUpdate(noteId, { isTrashed: true, isFavourite: false, isArchived: false });
  }

  @rpc
  async untrashNote(noteId: string): Promise<void> {
    this.notes.mutate((notes) => {
      const idx = notes.findIndex((n) => n.id === noteId);
      if (idx >= 0) notes[idx].isTrashed = false;
    });
    await this.persistNoteUpdate(noteId, { isTrashed: false });
  }

  @rpc
  async permanentlyDeleteNote(noteId: string): Promise<void> {
    const note = this.notes.find((n) => n.id === noteId);
    const noteDate = note ? this.getNoteDate(note) : null;
    this.notes.set(this.notes.filter((n) => n.id !== noteId));
    if (noteDate) await this.persistNoteDelete(noteId, noteDate);
    const conversationManager = (this._session as any)?.conversation;
    if (conversationManager?.clearNoteLink) conversationManager.clearNoteLink(noteId);
  }

  @rpc
  async emptyNoteTrash(): Promise<number> {
    const userId = this._session?.userId;
    const trashed = (this.notes as unknown as NoteData[]).filter((n) => n.isTrashed);
    console.log(`[NotesManager] Emptying trash: ${trashed.length} notes`);

    if (userId) {
      await deleteTrashedNotes(userId);
    }

    // Clear noteId links from conversations that referenced these notes
    const conversationManager = (this._session as any)?.conversation;
    if (conversationManager?.clearNoteLink) {
      for (const note of trashed) {
        conversationManager.clearNoteLink(note.id);
      }
    }

    this.notes.set((this.notes as unknown as NoteData[]).filter((n) => !n.isTrashed));
    console.log(`[NotesManager] Trash emptied: ${trashed.length} notes permanently deleted`);
    return trashed.length;
  }

  // ── Batch operations for multi-select ──

  @rpc
  async batchFavouriteNotes(noteIds: string[]): Promise<void> {
    for (const id of noteIds) await this.favouriteNote(id);
  }

  @rpc
  async batchTrashNotes(noteIds: string[]): Promise<void> {
    for (const id of noteIds) await this.trashNote(id);
  }

  @rpc
  async batchMoveNotes(noteIds: string[], folderId: string): Promise<void> {
    for (const id of noteIds) await this.updateNote(id, { folderId });
  }

  @rpc
  async exportNotesAsText(noteIds: string[]): Promise<string> {
    const parts: string[] = [];
    for (const id of noteIds) {
      const note = this.notes.find((n) => n.id === id);
      if (!note) continue;
      const content = (note.content || "")
        .replace(/<[^>]+>/g, " ")
        .replace(/&nbsp;/g, " ")
        .replace(/\s+/g, " ")
        .trim();
      parts.push(`# ${note.title || "Untitled Note"}\n${content}`);
    }
    return parts.join("\n\n---\n\n");
  }
}
