/**
 * Note Model
 *
 * Stores user notes - both manual and AI-generated.
 * Notes can optionally be linked to a transcript time range.
 */

import mongoose, { Schema, Document, Model } from "mongoose";
import { embedNote } from "../services/embedding.service";

// =============================================================================
// Interfaces
// =============================================================================

export interface NoteI extends Document {
  userId: string;
  title: string;
  summary: string;
  content: string;
  isStarred: boolean;
  isAIGenerated: boolean; // Whether this note was generated by AI or created manually
  date: string; // Folder date in YYYY-MM-DD format (which day this note belongs to)
  folderId?: string; // Optional folder assignment
  embedding: number[];
  transcriptRange?: {
    startTime: Date;
    endTime: Date;
  };
  createdAt: Date;
  updatedAt: Date;
}

// =============================================================================
// Schema
// =============================================================================

const NoteSchema = new Schema<NoteI>(
  {
    userId: { type: String, required: true, index: true },
    title: { type: String, required: true },
    summary: { type: String, default: "" },
    content: { type: String, default: "" },
    isStarred: { type: Boolean, default: false },
    isAIGenerated: { type: Boolean, default: false }, // Whether AI generated or manual
    date: { type: String, required: true, index: true }, // Folder date in YYYY-MM-DD format
    folderId: { type: String, default: null }, // Optional folder assignment
    embedding: { type: [Number], default: [] },
    transcriptRange: {
      startTime: { type: Date },
      endTime: { type: Date },
    },
  },
  { timestamps: true },
);

// Index for efficient user queries sorted by creation date
NoteSchema.index({ userId: 1, createdAt: -1 });

// =============================================================================
// Model
// =============================================================================

export const Note: Model<NoteI> =
  mongoose.models.Note || mongoose.model<NoteI>("Note", NoteSchema);

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Create a new note
 */
export async function createNote(
  userId: string,
  data: {
    title: string;
    content?: string;
    summary?: string;
    date: string; // Required: folder date in YYYY-MM-DD format
    isAIGenerated?: boolean;
    transcriptRange?: { startTime: Date; endTime: Date };
  },
): Promise<NoteI> {
  const note = await Note.create({
    userId,
    title: data.title,
    content: data.content || "",
    summary: data.summary || "",
    date: data.date,
    isAIGenerated: data.isAIGenerated ?? false,
    transcriptRange: data.transcriptRange,
  });

  // Fire-and-forget: generate embedding async
  embedNote(note._id!.toString(), data.title, data.content || "").catch(() => {});

  return note;
}

/**
 * Get all notes for a user
 */
export async function getNotes(userId: string): Promise<NoteI[]> {
  return Note.find({ userId }).sort({ createdAt: -1 });
}

/**
 * Get a single note by ID
 */
export async function getNoteById(
  userId: string,
  noteId: string,
): Promise<NoteI | null> {
  return Note.findOne({ _id: noteId, userId });
}

/**
 * Update a note
 */
export async function updateNote(
  userId: string,
  noteId: string,
  data: Partial<{
    title: string;
    content: string;
    summary: string;
    isStarred: boolean;
    folderId: string | null;
  }>,
): Promise<NoteI | null> {
  const note = await Note.findOneAndUpdate(
    { _id: noteId, userId },
    { $set: data },
    { new: true },
  );

  // Fire-and-forget: regenerate embedding if title or content changed
  if (note && (data.title !== undefined || data.content !== undefined)) {
    embedNote(noteId, note.title, note.content).catch(() => {});
  }

  return note;
}

/**
 * Delete a note
 */
export async function deleteNote(
  userId: string,
  noteId: string,
): Promise<boolean> {
  const result = await Note.deleteOne({ _id: noteId, userId });
  return result.deletedCount > 0;
}

/**
 * Get notes by date range (based on createdAt)
 */
export async function getNotesByDateRange(
  userId: string,
  startDate: Date,
  endDate: Date,
): Promise<NoteI[]> {
  return Note.find({
    userId,
    createdAt: { $gte: startDate, $lte: endDate },
  }).sort({ createdAt: -1 });
}

/**
 * Delete all notes for a specific date (YYYY-MM-DD)
 * Returns the number of deleted notes
 */
/**
 * Unassign all notes from a folder (set folderId to null)
 */
export async function unassignNotesFromFolder(
  userId: string,
  folderId: string,
): Promise<number> {
  const result = await Note.updateMany(
    { userId, folderId },
    { $set: { folderId: null } },
  );
  return result.modifiedCount;
}

/**
 * Delete all notes for a specific date (YYYY-MM-DD)
 * Returns the number of deleted notes
 */
export async function deleteNotesByDate(
  userId: string,
  date: string,
): Promise<number> {
  const result = await Note.deleteMany({
    userId,
    date: date,
  });

  return result.deletedCount;
}
