/**
 * Notes App Synced Types
 *
 * Shared types for frontend and backend.
 * Import these on the frontend for full type safety with useSynced().
 */

// =============================================================================
// Domain Types
// =============================================================================

export interface TranscriptSegment {
  id: string;
  text: string;
  timestamp: Date;
  isFinal: boolean;
  speakerId?: string;
  type?: "transcript" | "photo";
  photoUrl?: string;
  photoMimeType?: string;
  photoDescription?: string;
  timezone?: string;
}

export interface Note {
  id: string;
  title: string;
  content: string;
  summary?: string;
  date: string; // Folder date in YYYY-MM-DD format (which day this note belongs to)
  isAIGenerated: boolean; // Whether this note was generated by AI or created manually
  createdAt: Date;
  updatedAt: Date;
  transcriptRange?: {
    startTime: Date;
    endTime: Date;
  };
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

/**
 * Rolling summary of what happened during a specific hour
 * Generated automatically as hours complete
 */
export interface HourSummary {
  id: string;
  date: string; // YYYY-MM-DD in user's timezone
  hour: number; // 0-23
  hourLabel: string; // "9 AM", "2 PM", etc.
  summary: string; // AI-generated 1-2 sentence summary
  segmentCount: number; // Number of transcript segments in this hour
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Display modes for glasses
 */
export type GlassesDisplayMode =
  | "off" // Nothing shown on glasses
  | "live_transcript" // Real-time transcription text
  | "hour_summary" // Rolling hour description/summary
  | "key_points"; // Only show when AI detects something important

// =============================================================================
// Manager Interfaces (State + RPCs)
// =============================================================================

export interface TranscriptManagerI {
  // State (auto-syncs)
  segments: TranscriptSegment[];
  interimText: string;
  isRecording: boolean;
  loadedDate: string; // Currently loaded date (YYYY-MM-DD)
  availableDates: string[]; // Dates with transcripts (for folder list)
  isLoadingHistory: boolean; // Loading indicator for historical data
  isSyncingPhoto: boolean; // True while a photo is being uploaded/analyzed

  // RPCs
  getRecentSegments(count?: number): Promise<TranscriptSegment[]>;
  getFullText(): Promise<string>;
  clear(): Promise<void>;
  loadDateTranscript(date: string): Promise<{
    segments: TranscriptSegment[];
    hourSummaries: HourSummary[];
  }>; // Load historical transcript
  loadTodayTranscript(): Promise<void>; // Switch back to today
}

export interface SummaryManagerI {
  // State (auto-syncs)
  hourSummaries: HourSummary[];
  currentHourSummary: string; // Rolling summary for glasses display

  // RPCs
  generateHourSummary(hour?: number): Promise<HourSummary>;
  refreshHourSummary(): Promise<string>; // Force immediate summary update
}

export interface NotesManagerI {
  // State
  notes: Note[];
  generating: boolean;

  // RPCs
  generateNote(title?: string, startTime?: Date, endTime?: Date): Promise<Note>;
  createManualNote(title: string, content: string): Promise<Note>;
  updateNote(noteId: string, updates: Partial<Note>): Promise<Note>;
  deleteNote(noteId: string): Promise<void>;
  getNoteById(noteId: string): Promise<Note | null>;
  getAllNotes(): Promise<Note[]>;
}

export interface ChatManagerI {
  // State
  messages: ChatMessage[];
  isTyping: boolean;
  loadedDate: string; // Currently loaded date (YYYY-MM-DD)

  // RPCs
  sendMessage(content: string): Promise<ChatMessage>;
  clearHistory(): Promise<void>;
  loadDateChat(date: string): Promise<ChatMessage[]>; // Load chat for specific date
}

export interface SettingsManagerI {
  // State
  showLiveTranscript: boolean;
  displayName: string | null;
  timezone: string | null; // IANA timezone e.g. "America/Los_Angeles"
  glassesDisplayMode: GlassesDisplayMode;
  superCollapsed: boolean;

  // RPCs
  updateSettings(settings: {
    showLiveTranscript?: boolean;
    displayName?: string;
    timezone?: string;
    glassesDisplayMode?: GlassesDisplayMode;
    superCollapsed?: boolean;
  }): Promise<void>;
}

/**
 * File data - represents a folder/date in the UI
 */
export interface FileData {
  id: string;
  date: string; // YYYY-MM-DD
  noteCount: number;
  transcriptSegmentCount: number;
  transcriptHourCount: number;
  hasTranscript: boolean;
  hasNotes: boolean;
  isArchived: boolean;
  isTrashed: boolean;
  isFavourite: boolean;
  r2Key?: string;
  createdAt: Date;
  updatedAt: Date;
}

export type FileFilter = "all" | "archived" | "trash" | "favourites";

export interface FileCounts {
  all: number;
  archived: number;
  trash: number;
  favourites: number;
}

export interface FileManagerI {
  // State
  files: FileData[];
  isLoading: boolean;
  activeFilter: FileFilter;
  counts: FileCounts;

  // RPCs
  refreshFiles(): Promise<FileData[]>;
  getFilesRpc(filter?: FileFilter): Promise<FileData[]>;
  setFilter(filter: FileFilter): Promise<FileData[]>;
  archiveFile(date: string): Promise<FileData | null>;
  unarchiveFile(date: string): Promise<FileData | null>;
  trashFile(date: string): Promise<FileData | null>;
  restoreFile(date: string): Promise<FileData | null>;
  favouriteFile(date: string): Promise<FileData | null>;
  unfavouriteFile(date: string): Promise<FileData | null>;
  permanentlyDeleteFile(date: string): Promise<boolean>;
  purgeDate(date: string): Promise<{ deletedTranscript: boolean; deletedFile: boolean }>;
  emptyTrash(): Promise<{ deletedCount: number; errors: string[] }>;
}

// =============================================================================
// Session Interface
// =============================================================================

export interface SessionI {
  userId: string;

  // Session-level state
  hasGlassesConnected: boolean;
  hasActiveSession: boolean;
  isRecording: boolean;

  // Managers
  transcript: TranscriptManagerI;
  summary: SummaryManagerI;
  notes: NotesManagerI;
  chat: ChatManagerI;
  settings: SettingsManagerI;
  file: FileManagerI;
}

// =============================================================================
// WebSocket Message Types
// =============================================================================

export type WSMessageToClient =
  | { type: "connected" }
  | { type: "snapshot"; state: Record<string, any> }
  | { type: "state_change"; manager: string; property: string; value: any }
  | { type: "rpc_response"; id: string; result?: any; error?: string };

export type WSMessageToServer =
  | { type: "request_snapshot" }
  | {
      type: "rpc_request";
      id: string;
      manager: string;
      method: string;
      args: any[];
    };
